export const Routes = {
  home: "/",
  faculties: "/faculties",
  majors: "/majors",
  teachers: "/teachers",
  modules: "/modules",
  students: "/students",
  topics: "/topics",
  documents: "/documents",
  chooseTopics: "/chose-topics",
  outlines: "/outlines",
  login: "/login",
  proposalTopics: "/proposal-topics",
  approveTopics: "/approve-topics",
  theses: "/theses",
  registerThesis: "/register-thesis",
  resultTheses: "/result-theses",
  assignReviewTeachers: "/assign-review-teachers",
  councils: "/councils",
  reportTheses: "/report-theses",
  reportCompleteTheses: "/report-complete-theses",
  reportNumberStudentOfTeacher: "/report-number-student-of-teacher",
  schoolYears: "/school-years",
  semesters: "/semesters",
};
