export const Routes = {
  home: "/",
  faculties: "/faculties",
  majors: "/majors",
  teachers: "/teachers",
  modules: "/modules",
  students: "/students",
  topics: "/topics",
  documents: "/documents",
  chooseTopics: "/chose-topics",
  outlines: "/outlines",
  login: "/login",
  proposalTopics: "/proposal-topics",
  approveTopics: "/approve-topics",
};
